# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a142fc7b75e102386be427b7e18d005072e78eb672c46bafcf99800768860ea6731731d94a2013823cba20e45fc666161e3ff3e1e5f946e6cbb0dfa8dd4e8d3

test:
  secret_key_base: c7b0ca0a0e38c9604c249bd79e7740871991a1c4b0ef315d2141e22eb5eef719d8b8a9c859bdcc61e36593be613c5e2f205ed856f7d597f008e60ee4311e53e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
